# Generated by Django 2.1 on 2018-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapa_id', models.IntegerField(verbose_name='tapd单号')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('release_time', models.DateTimeField(verbose_name='上线时间')),
                ('environment', models.CharField(max_length=200, verbose_name='环境')),
                ('tester', models.CharField(max_length=200, verbose_name='测试人员')),
                ('developer', models.CharField(max_length=200, verbose_name='开发人员')),
                ('project', models.CharField(max_length=600, verbose_name='Project')),
                ('comments', models.CharField(max_length=1000, verbose_name='Comments')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='新增时间')),
            ],
        ),
    ]
